# Generated by Django 2.0.7 on 2018-07-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('puntaje', models.IntegerField()),
                ('posicion_old', models.IntegerField()),
                ('posicion', models.IntegerField()),
            ],
        ),
    ]
