# Generated by Django 2.0.7 on 2018-07-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='posicion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='posicion_old',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='puntaje',
            field=models.IntegerField(null=True),
        ),
    ]
